extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

  opencensus:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

processors:
  batch:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

exporters:
  otlp/lightstep:
    endpoint: ingest.lightstep.com:443
    headers:
      "lightstep-access-token": "2BLMx6IYg+mWEb399UU+FWk96efTod5lD3cae1v91behFLuAtTbSJrXjSMOlKi3TivkqNVnzTk03xLxbKIEhMm368HQvtUwiEg3ANO4q"

service:
  pipelines:
    traces:
      receivers: [otlp, opencensus, jaeger, zipkin]
      processors: [resourcedetection, batch]
      exporters: [otlp/lightstep]

    metrics:
      receivers: [otlp, opencensus, prometheus]
      processors: [resourcedetection, batch]
      exporters: [otlp/lightstep]

  extensions: [health_check, pprof, zpages]